Models/Products.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace bigSales.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; } = string.Empty;

        [Required]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }

        [StringLength(500)]
        public string Description { get; set; } = string.Empty;

        public string? ImagePath { get; set; }
        public int CategoryId { get; set; }

        [ForeignKey("CategoryId")]
        public Category? Category { get; set; }
    }
}

Controllers/CategoryController.cs
using bigSales.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace bigSales.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }


        public IActionResult Rods()
        {
            var products = _context.Products
                .Include(p => p.Category)
                .Where(p => p.CategoryId == 1)
                .ToList();

            return View(products);
        }


        public IActionResult Reels()
        {
            var products = _context.Products
                .Include(p => p.Category)
                .Where(p => p.CategoryId == 2)
                .ToList();

            return View(products);
        }


        public IActionResult Lures()
        {
            var products = _context.Products
                .Include(p => p.Category)
                .Where(p => p.CategoryId == 3)
                .ToList();

            return View(products);
        }
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using bigSales.Models;
using bigSales.Services;
using Microsoft.AspNetCore.Authorization;

namespace bigSales.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductService _productService;

        public ProductsController(ProductService productService)
        {
            _productService = productService;
        }

        public IActionResult ProductsList()
        {
            var products = _productService.GetAllProducts();
            return View(products);
        }

        public IActionResult AllProducts()
        {
            var products = _productService.GetAllProducts();
            return View(products);
        }

        public IActionResult Details()
        {
            return View();
        }


    }
}

Views/Products/AllProducts.cshtml
@model IEnumerable<bigSales.Models.Product>

    @{
        Layout = "~/Views/Shared/_Layout.cshtml";  // Gerekiyorsa layout dosyasını ayarlayın
    }
    
    <section class="inner_page_head">
        <div class="container_fuild">
            <div class="row">
                <div class="col-md-12">
                    <div class="heading_container heading_center">
                        <h2>Ürünlerimiz</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="product_section layout_padding">
        <div class="container">
            <div class="row">
                @foreach (var product in Model)
                {
                    <div class="col-sm-6 col-md-4 col-lg-3">
                        <div class="box">
                            <div class="option_container">
                                <div class="options">
                                    <a asp-controller="Products" asp-action="Details" asp-route-id="@product.Id" class="option1">
                                        Ürünü İncele
                                    </a>
                                    <a asp-controller="Cart" asp-action="Add" asp-route-productId="@product.Id" class="option2">
                                        Sepete Ekle
                                    </a>
                                </div>
                            </div>
                            <div class="img-box">
                                <img src="@product.ImagePath" alt="@product.Name" />
                            </div>
                            <div class="detail-box">
                                <h5>@product.Name</h5>
                                <h6 class="price">@string.Format("{0:C}", product.Price)</h6>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
    

Views/Products/Details.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<bigSales.Models.Product>

<div class="container">
    asdsadsa
</div>

Views/Products/ProductsList.cshtml
@model IEnumerable<bigSales.Models.Product>

   @{
   Layout = "~/Views/Shared/_Layout.cshtml"; // Kullanıcılar için genel layout
   }

   <section class="inner_page_head">
      <div class="container_fuild">
         <div class="row">
            <div class="col-md-12">
               <div class="full">
                  <h3>Olta Ekipmanları</h3>
               </div>
            </div>
         </div>
      </div>
   </section>

   <div class="three_box">
      <div class="container">
         <div style="row-gap: 15px;" class="row">
            <div class="col-md-4">
               <a asp-controller="Category" asp-action="Rods" class="allrods">
                  <div class="box_text">
                     <i><img style="width: 100%;max-width: 200px;" src="~/images/rod.png" alt="#" /></i>
                     <h3>Olta Kamışları</h3>
                     <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                        alteration in some form, by injected humour, or randomised words which don't look even slightly
                        believable. </p>
                  </div>
               </a>
            </div>
            <div class="col-md-4">
               <a asp-controller="Category" asp-action="Reels" class="allreels">
                  <div class="box_text">
                     <i><img style="width: 100%;max-width: 200px;" src="~/images/reels.jpg" alt="#" /></i>
                     <h3>Olta Makineleri</h3>
                     <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                        alteration in some form, by injected humour, or randomised words which don't look even slightly
                        believable. </p>
                  </div>
               </a>
            </div>
            <div class="col-md-4">
               <a asp-controller="Category" asp-action="Lures" class="alllures">
                  <div class="box_text">
                     <i><img style="width: 100%;max-width: 300px;" src="~/images/lure.jpg" alt="#" /></i>
                     <h3>Yemler</h3>
                     <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                        alteration in some form, by injected humour, or randomised words which don't look even slightly
                        believable. </p>
                  </div>
               </a>
            </div>
         </div>
      </div>
      <section style="padding: 0 !important;" class="product_section layout_padding">
         <div class="container">
            <div class="btn-box">
               <a asp-controller="Products" asp-action="AllProducts" class="btn btn-secondary">Tüm Ürünleri Görüntüle</a>
            </div>
         </div>
      </section>
   </div>